services:
  spring_boot:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./compose/spring_boot/Dockerfile
    networks:
      - backend
    ports:
      - 9090:8080
    volumes:
      - spring_boot:/project/.m2
    restart: unless-stopped
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bassid_demo_database
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend
    ports:
      - "5050:80"
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  spring_boot:
  postgres:
  pgadmin:
